CREATE DATABASE BD_10
GO

USE BD_10
GO

-- Inserindo tabela
SELECT * FROM Pessoa

-- Exercício 01
SELECT uf, COUNT(uf) AS REGISTROS_UF FROM Pessoa
GROUP BY uf 

-- Exercício 02
SELECT uf AS UNIDADE_FEDERATIVA, COUNT(uf) AS REGISTROS_UF, SUM(idade) AS SOMA_IDADE  FROM Pessoa
GROUP BY uf 

-- Exercício 03
SELECT uf AS UNIDADE_FEDERATIVA, COUNT(uf) AS REGISTROS_UF, AVG(idade) AS MÉDIA_IDADE  FROM Pessoa 
GROUP BY uf ORDER BY AVG(idade) DESC

-- Exercício 04
SELECT uf AS UNIDADE_FEDERATIVA, COUNT(uf) AS REGISTROS_UF, MAX(idade) AS IDADE_MÁXIMA, MIN(idade) IDADE_MINÍMA  FROM Pessoa 
GROUP BY uf ORDER BY MAX(idade), MIN(idade) ASC

-- Exercício 05
SELECT uf AS UNIDADE_FEDERATIVA, sexo AS SEXO, COUNT(sexo) AS REGISTROS_UF FROM Pessoa
GROUP BY uf, sexo

